
CREATE TABLE al_film (
    id SERIAL PRIMARY KEY,
    title TEXT,
    name VARCHAR(255),
    title_orig TEXT,
    original_name VARCHAR(255),
    countries VARCHAR(255),
    link TEXT,
    poster_url TEXT,
    alternative_name TEXT,
    year INTEGER,
    id_kp INTEGER,
    alternative_id_kp INTEGER,
    id_imdb VARCHAR(20),
    id_tmdb INTEGER,
    token_movie VARCHAR(255),
    date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    category VARCHAR(100),
    genre TEXT,
    actors TEXT,
    directors TEXT,
    producers TEXT,
    premiere_ru VARCHAR(20),
    premiere VARCHAR(20),
    age_restrictions INTEGER,
    rating_kp FLOAT,
    rating_imdb FLOAT,
    time VARCHAR(20),
    poster VARCHAR(500),
    description TEXT,
    iframe VARCHAR(500),
    quality VARCHAR(50),
    translation VARCHAR(100),
    translation_iframe JSON,
    lgbt BOOLEAN DEFAULT FALSE,
    uhd BOOLEAN DEFAULT FALSE
);