"""Create table AnimeOva

Revision ID: 564b7460b382
Revises: 
Create Date: 2024-09-26 22:17:50.222687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '564b7460b382'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anime_main_title')
    op.drop_table('anime_schema')
    op.drop_column('anime_ova', 'seasons')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anime_ova', sa.Column('seasons', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.create_table('anime_schema',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('link', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title_orig', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_season', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_episode', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('episodes_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('kinopoisk_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('imdb_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('worldart_link', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('shikimori_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('quality', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('camrip', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('lgbt', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('blocked_countries', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('blocked_seasons', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('seasons', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('material_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('screenshots', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='anime_schema_pkey')
    )
    op.create_table('anime_main_title',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('link', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title_orig', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_season', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_episode', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('episodes_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('kinopoisk_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('imdb_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('worldart_link', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('shikimori_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('quality', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('camrip', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('lgbt', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('blocked_countries', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('blocked_seasons', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('seasons', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('material_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('screenshots', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='anime_main_title_pkey')
    )
    # ### end Alembic commands ###
